In [1]:
import pandas as pd
import numpy as np

In [12]:
raw_data= {'regiment':['Nighthawks','Nighthawks','Nighthawks','Nighthawks','Dragons','Dragons','Dragons','Dragons','Scouts','Scouts','Scouts','Scouts'],
          'company':['1st','1st','2nd','2nd','1st','1st','2nd','2nd','1st','1st','2nd','2nd'],
          'postTestScore':[25,94,57,62,70,25,94,57,62,70,62,70]}
df = pd.DataFrame(raw_data,columns=['regiment','company','postTestScore'])
df

regiment company  postTestScore
0   Nighthawks     1st             25
1   Nighthawks     1st             94
2   Nighthawks     2nd             57
3   Nighthawks     2nd             62
4      Dragons     1st             70
5      Dragons     1st             25
6      Dragons     2nd             94
7      Dragons     2nd             57
8       Scouts     1st             62
9       Scouts     1st             70
10      Scouts     2nd             62
11      Scouts     2nd             70

In [13]:
bins = [0,25,50,75,100] # Define bins as 0 to 25, 25 to 50, 60 to 75, 75 to 100
group_names = ['Low','Okay','Good','Great'] #구간명
categorise = pd.cut(df['postTestScore'],bins,labels=group_names)
# Cut 후 categirues에 할당
categorise

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): [Low < Okay < Good < Great]

In [16]:
df['categorise'] = categorise
df

regiment company  postTestScore categorise
0   Nighthawks     1st             25        Low
1   Nighthawks     1st             94      Great
2   Nighthawks     2nd             57       Good
3   Nighthawks     2nd             62       Good
4      Dragons     1st             70       Good
5      Dragons     1st             25        Low
6      Dragons     2nd             94      Great
7      Dragons     2nd             57       Good
8       Scouts     1st             62       Good
9       Scouts     1st             70       Good
10      Scouts     2nd             62       Good
11      Scouts     2nd             70       Good

In [17]:
pd.value_counts(df['categorise'])

Good     8
Great    2
Low      2
Okay     0
Name: categorise, dtype: int64

In [18]:
pd.get_dummies(df)

postTestScore  regiment_Dragons  regiment_Nighthawks  regiment_Scouts  \
0              25                 0                    1                0   
1              94                 0                    1                0   
2              57                 0                    1                0   
3              62                 0                    1                0   
4              70                 1                    0                0   
5              25                 1                    0                0   
6              94                 1                    0                0   
7              57                 1                    0                0   
8              62                 0                    0                1   
9              70                 0                    0                1   
10             62                 0                    0                1   
11             70                 0                    0                1   

    company_1st  company_2nd  categorise_Low  categorise_Okay  \
0             1            0               1                0   
1             1            0               0                0   
2             0            1               0                0   
3             0            1               0                0   
4             1            0               0                0   
5             1            0               1                0   
6             0            1               0                0   
7             0            1               0                0   
8             1            0               0                0   
9             1            0               0                0   
10            0            1               0                0   
11            0            1               0                0   

    categorise_Good  categorise_Great  
0                 0                 0  
1                 0                 1  
2                 1                 0  
3                 1                 0  
4                 1                 0  
5                 0                 0  
6                 0                 1  
7                 1                 0  
8                 1                 0  
9                 1                 0  
10                1                 0  
11                1                 0

In [19]:
raw_example = df.values

In [21]:
data = raw_example.copy()

In [24]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [28]:
le.fit(raw_example[:,0])

LabelEncoder()

In [31]:
#데이터 라벨링
le.transform(raw_example[:,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [33]:
#데이터 변경하기
data[:,0] = le.transform(raw_example[:,0])
data[:3]

array([[1, '1st', 25, 'Low'],
       [1, '1st', 94, 'Great'],
       [1, '2nd', 57, 'Good']], dtype=object)

In [36]:
label_column = [0,1,2,3]
lable_enconder_list = []
for column_index in label_column:
    le = preprocessing.LabelEncoder()
    le.fit(raw_example[:,column_index])
    data[:,column_index] = le.transform(raw_example[:,column_index])
    lable_enconder_list.append(le) #기존 label encoder를 따로 저장
    del le
data[:3]

array([[1, 0, 0, 2],
       [1, 0, 4, 1],
       [1, 1, 1, 0]], dtype=object)

In [37]:
lable_enconder_list[0].transform(raw_example[:10,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2])